language: python

python:
  - 2.7
  - 3.6

sudo: required

before_install:
  - sudo apt-get install -y --no-install-recommends python-numpy-dev 


install:
  - pip install -U pip pip-tools
  - pip install numpy scipy scikit-learn

script:
  - make $TEST_SUITE

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

env:
- TEST_SUITE=test_python.out
