controller_list:
  - name: arm/arm_joint_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - base_link__link_01
      - link_01__link_02
      - link_02__link_03
      - link_03__link_04
      - link_04__link_05
      - link_05__link_06
  - name: arm/gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - link_06__finger_1
      - link_06__finger_2